/*
=============================================================================
[파일 설명서] data.js (상하 완전 분리형 Database)
- 수정 가이드:
  한국어 데이터 그룹(ko)과 영어 데이터 그룹(en)이 상/하로 나뉘어 있습니다.
  한국어의 N번째 줄은 영어의 N번째 줄과 1:1로 매칭됩니다.
=============================================================================
*/

const JEWEL_DATABASE = {
    ko: [
        // ["한국명", "전설능력", "신화능력", "색상(Hex)"]
        ["가넷", "공격력+200%,공격속도-30%", "공격력+250%,공격속도+30%", "#ff1e1e"],
        ["아메시스트", "유닛가속+25%,이동속도+100%", "유닛가속+40%,이동속도+150%", "#9d4edd"],
        ["아쿠아마린", "RXD 등급 부여", "2마리 동시 장착 시 SXD 등급 부여", "#4cc9f0"],
        ["다이아몬드", "한계 돌파 시 파괴 방지", "가스 40 환급 및 초기화", "#ffffff"],
        ["에메랄드", "5단계 이상 총 데미지 +30%", "3단계 이상 총 데미지 +45%", "#2ecc71"],
        ["펄", "유닛 강화 수치 +100%", "유닛 강화 수치 +200%", "#fefae0"],
        ["루비", "공격력 +150%, 이동속도 -75%", "공격력 +250%, 이동속도 +100%", "#e63946"],
        ["페리도트", "탐지 부여 (범위 8)", "탐지 부여 (범위 12) + 공력 100%", "#aacc00"],
        ["사파이어", "가속 2배 (60분)", "90분 가속 2배 후 가속 +33% 영구 적용", "#0077b6"],
        ["오팔", "쥬얼 장착 횟수 +3", "쥬얼 장착 횟수 +6, 공격력 +125%", "#ffafcc"],
        ["토파즈", "공격속도 +15%, 2마리까지 동시에 장착 가능", "", "#ffd700"],
        ["터쿼이즈", "랩터 잭팟 확률이 3배로 적용", "", "#40e0d0"],
        ["블러드스톤", "총 데미지 +20%, 장착 시 9% 확률로 유닛 파괴됨", "", "#8a0303"],
        ["스피넬", "20분 이후 유닛 가속 +30%", "", "#ff4d4d"],
        ["플로라이트", "30분 동안 총 데미지 -80%, 이후 총 데미지 +20%", "", "#90ee90"],
        ["라피스", "10의 배수 라운드마다 공격력 +10% (최대 20번)", "", "#0000ff"],
        ["헬리오도르", "공격력 +200%, 이후 20의 배수 라운드마다 공격력 -10%", "", "#dfdf00"],
        ["제트", "총 데미지 +20%, 반드시 유닛 2마리 선택 (한 유닛만 효과 적용)", "", "#1a1a1a"],
        ["아게이트", "유닛 가속 +9%, 3마리 동시 장착 가능 (각각 5/15% 파괴 확률)", "", "#e0af1f"],
        ["올리빈", "해당 쥬얼의 최종 강화 확률 10배, 강화 효과 3배 적용", "", "#9ab973"],
        ["히아신스", "공격력 +150%, 사거리 +3, 이동 불가", "", "#ff8c00"],
        ["크리소베릴", "모든 기본 스탯이 최대치로 적용", "", "#dfff00"],
        ["파파라챠", "108분 후 총 데미지 +33%", "", "#ff8b61"],
        ["탄자나이트", "유닛 2마리의 강화/한계돌파 수치 교체", "", "#483d8b"],
        ["루벨라이트", "총 데미지 & 유닛 가속 +25%, 1% 확률로 파괴", "", "#e0115f"]
    ],
    en: [
        // ["영어명", "영어전설능력", "영어신화능력"]
        ["Garnet", "ATK +200%, ATK SPD -30%", "ATK +250%, ATK SPD +30%"],
        ["Amethyst", "Unit Accel +25%, Move SPD +100%", "Unit Accel +40%, Move SPD +150%"],
        ["Aquamarine", "Grants RXD Grade", "Grants SXD Grade if 2 equipped"],
        ["Diamond", "Prevents destruction on Limit Break", "Refunds 40 Gas & Resets"],
        ["Emerald", "Stage 5+ Total DMG +30%", "Stage 3+ Total DMG +45%"],
        ["Pearl", "Unit Enhancement +100%", "Unit Enhancement +200%"],
        ["Ruby", "ATK +150%, Move SPD -75%", "ATK +250%, Move SPD +100%"],
        ["Peridot", "Grants Detection (Range 8)", "Grants Detection (Range 12) + ATK 100%"],
        ["Sapphire", "Accel x2 (60 min)", "Accel x2 for 90 min, then +33% Accel permanently"],
        ["Opal", "Jewel Equip Slots +3", "Jewel Equip Slots +6, ATK +125%"],
        ["Topaz", "ATK SPD +15%, Max 2 equipped at once", ""],
        ["Turquoise", "Raptor Jackpot chance x3", ""],
        ["Bloodstone", "Total DMG +20%, 9% chance to destroy unit when equipped", ""],
        ["Spinel", "Unit Accel +30% after 20 mins", ""],
        ["Fluorite", "Total DMG -80% for 30 mins, then Total DMG +20%", ""],
        ["Lapis", "ATK +10% every 10 rounds (Max 20 times)", ""],
        ["Heliodor", "ATK +200%, then ATK -10% every 20 rounds", ""],
        ["Jet", "Total DMG +20%, Must choose 2 units (effect applied to one)", ""],
        ["Agate", "Unit Accel +9%, Can equip 3 at once (5/15% destroy chance each)", ""],
        ["Olivine", "Final Enhance Chance x10, Enhance Effect x3", ""],
        ["Hyacinth", "ATK +150%, Range +3, Immobile", ""],
        ["Chrysoberyl", "All basic stats reach maximum", ""],
        ["Padparadscha", "Total DMG +33% after 108 mins", ""],
        ["Tanzanite", "Swap Enhance/Limit Break stats of 2 units", ""],
        ["Rubellite", "Total DMG & Unit Accel +25%, 1% chance to destroy", ""]
    ]
};

const UNIT_DATABASE = {
    ko: [
        // === [ 테바 ] ===
        ["전쟁광", "매직", "테바", "", ""],
        ["저격수", "매직", "테바", "", ""],
        ["망치경호대", "매직", "테바", "", ""],
        ["죽음의머리", "레어", "테바", "전쟁광[1]+망치경호대[1]", "전쟁광[1],망치경호대[1]"],
        ["악령", "레어", "테바", "저격수[1]+망치경호대[1]", "저격수[1],망치경호대[1]"],
        ["짐레이너", "에픽", "테바", "죽음의머리[1]+악령[1]", "전쟁광[1],저격수[1],망치경호대[2]"],
        ["스투코프", "유니크", "테바", "짐레이너[1]+케리건[1]", "전쟁광[1],저격수[1],망치경호대[2],원시바퀴[1],변종가시지옥[1],원시히드라리스크[2]"],
        ["노바", "헬", "테바", "스투코프[2]+혼종파멸자[1]", "전쟁광[3],저격수[3],망치경호대[6],원시바퀴[2],변종가시지옥[2],원시히드라리스크[4]"],
        ["특공대레이너", "레전드", "테바", "노바[1]+워필드장군[1]", "전쟁광[4],저격수[8],망치경호대[12],암흑광전사[1],암흑고위기사[1],암흑집정관[2],원시바퀴[3],변종가시지옥[3],원시히드라리스크[6]"],
        ["가브리엘토시", "히든", "테바", "악령[2]+망치경호대[3]", "저격수[2],망치경호대[5]"],
        ["광부", "히든", "테바", "도우미(500킬↑)[1]+타우렌화장실[1]", "전쟁광[4],암흑불멸자[4],도우미[1]"],
        ["로리스완", "히든", "테바", "자치령불곰[2]+낮까마귀[1]+자동포탑[1]", "전쟁광[8],망치경호대[6],낮까마귀[1],자동포탑[5]"],
        ["마일스블레이즈루이스", "히든", "테바", "프로메테우스중대(X,90%↑)+자치령불곰[2]+빨정관(10킬이상)[1]", "암흑집정관[4],전쟁광[8],저격수[4],망치경호대[10],스파르타중대[4]"],
        ["멀록해병", "히든", "테바", "죽음의머리[3]+라바사우르스(잠복)[2]", "전쟁광[3],망치경호대[3],원시바퀴[2],원시히드라리스크[2]"],
        ["워필드장군", "히든", "테바", "스투코프[1]+악령[4]", "전쟁광[1],저격수[5],망치경호대[6],원시바퀴[1],변종가시지옥[1],원시히드라리스크[2]"],
        ["이곤스텟먼", "히든", "테바", "멀록해병[1]+타우렌화장실[1]", "전쟁광[7],망치경호대[3],암흑불멸자[4],원시바퀴[2],원시히드라리스크[2]"],
        ["자치령불곰", "히든", "테바", "타우렌우주해병[2]+망치경호대[3]", "전쟁광[4],망치경호대[3]"],
        ["타우렌우주해병", "히든", "테바", "전쟁광(SS↑)[2]", "전쟁광[2]"],
        ["타우렌화장실", "히든", "테바", "타우렌우주해병[2]+말살자[1]", "전쟁광[4],암흑불멸자[4]"],
        ["타이커스핀들레이", "히든", "테바", "로리스완(X↑)[1]+이곤스텟먼(X↑)[1]", "전쟁광[15],망치경호대[9],암흑불멸자[4],원시바퀴[2],원시히드라리스크[2],자동포탑[5]"],
        ["프로메테우스중대", "히든", "테바", "가브리엘토시(SSS↑)[2]+스파르타중대[4]", "저격수[4],망치경호대[10],스파르타중대[4]"],
        ["비밀작전노바", "슈퍼히든", "테바", "특공대레이너(SXD,300%↑,300킬↑)[1]+타이커스핀들레이(SXD,300%↑,300킬↑)[1]+오메가리스크(X↑,150%↑)[2]", "전쟁광[19],저격수[8],망치경호대[21],암흑광전사[5],암흑고위기사[5],암흑집정관[10],원시바퀴[15],변종가시지옥[13],원시히드라리스크[28],자동포탑[5]"],

        // === [ 테메 ] ===
        ["스파르타중대", "매직", "테메", "", ""],
        ["코브라", "매직", "테메", "", ""],
        ["공성파괴단", "매직", "테메", "", ""],
        ["검은망치", "레어", "테메", "스파르타중대[1]+공성파괴단[1]", "스파르타중대[1],공성파괴단[1]"],
        ["A.R.E.S", "레어", "테메", "코브라[1]+공성파괴단[1]", "코브라[1],공성파괴단[1]"],
        ["대천사", "에픽", "테메", "검은망치[1]+A.R.E.S[1]", "코브라[1],스파르타중대[1],공성파괴단[2]"],
        ["오딘", "유니크", "테메", "대천사[2]", "코브라[2],스파르타중대[2],공성파괴단[4]"],
        ["히페리온", "헬", "테메", "오딘[2]+공허포격기[1]", "코브라[5],스파르타중대[5],공성파괴단[10],암흑파수기[1],암흑추적자[1],암흑불멸자[2]"],
        ["고르곤전투순양함", "레전드", "테메", "히페리온[1]+과학선[1]", "코브라[11],스파르타중대[7],공성파괴단[18],암흑파수기[1],암흑추적자[1],암흑불멸자[2]"],
        ["과학선", "히든", "테메", "오딘[1]+A.R.E.S[4]", "코브라[6],스파르타중대[2],공성파괴단[8]"],
        ["낮까마귀", "히든", "테메", "땅거미지뢰[2]+투견[3]+통기레쓰[1]", "시체매-지뢰매설[24],코브라[3],스파르타중대[6],암흑광전사[2]"],
        ["대천사전투기", "히든", "테메", "대천사(SSS↑)[4]", "코브라[4],스파르타중대[4],공성파괴단[8]"],
        ["드라켄레이저천공기", "히든", "테메", "공성파괴단[3]+A.R.E.S[2]", "코브라[2],공성파괴단[5]"],
        ["땅거미지뢰", "히든", "테메", "거미지뢰(시체매로매설)[12]", "시체매-지뢰매설[12]"],
        ["아우구스트그라드의자랑", "히든", "테메", "고르곤전투순양함(남은강화횟수0,1000킬)[1]+검은망치(SSS)[4]", "코브라[11],스파르타중대[11],공성파괴단[22],암흑파수기[1],암흑추적자[1],암흑불멸자[2]"],
        ["제우스폭격기", "히든", "테메", "해적주력함(Lv11)[1]+폭격기(Lv11)[1]+메시브디제스터(스킬사용)[1]", "스파르타중대[21],코브라[22],공성파괴단[34],암흑광전사[2],암흑파수기[1],암흑추적자[1],암흑불멸자[2],시체매-지뢰매설[24],메시브디제스터[1]"],
        ["창공의분노", "히든", "테메", "대천사전투기(한계돌파3↑,500킬↑)[1]+분노수호자(X↑)[1]", "코브라[4],스파르타중대[4],공성파괴단[8],암흑파수기[2],암흑추적자[2],암흑불멸자[4]"],
        ["통기레쓰", "히든", "테메", "코브라[3]+암흑광전사[2]", "코브라[3],암흑광전사[2]"],
        ["투견", "히든", "테메", "스파르타중대(SS↑)[2]", "스파르타중대[2]"],
        ["폭격기", "히든", "테메", "낮까마귀(X↑)[1]+과학선(X↑)[1]", "시체매-지뢰매설[24],코브라[9],스파르타중대[8],공성파괴단[8],암흑광전사[2]"],
        ["핵의원천", "히든", "테메", "타우렌화장실[1]+통기레쓰[2]+빨정관[1]", "전쟁광[4],코브라[6],암흑광전사[4],암흑집정관[4],암흑불멸자[4]"],
        ["해적주력함", "히든", "테메", "대천사전투기[2]+히페리온(X↑,90%↑)[1]", "코브라[13],스파르타중대[13],공성파괴단[26],암흑파수기[1],암흑추적자[1],암흑불멸자[2]"],
        ["테라트론", "슈퍼히든", "테메", "고르곤전투순양함(SXD,300%↑,300킬↑)[1]+해적주력함(SXD,300%↑,300킬↑)[1]+로리스완(XD↑)[2]", "전쟁광[16],망치경호대[12],코브라[24],스파르타중대[20],공성파괴단[44],암흑파수기[2],암흑추적자[2],암흑불멸자[4],자동포탑[10]"],

        // === [ 토바 ] ===
        ["암흑광전사", "매직", "토바", "", ""],
        ["암흑고위기사", "매직", "토바", "", ""],
        ["암흑집정관", "매직", "토바", "", ""],
        ["광전사석상", "레어", "토바", "암흑광전사[1]+암흑집정관[1]", "암흑광전사[1],암흑집정관[1]"],
        ["정화자사도", "레어", "토바", "암흑고위기사[1]+암흑집정관[1]", "암흑고위기사[1],암흑집정관[1]"],
        ["제라툴", "에픽", "토바", "광전사석상[1]+정화자사도[1]", "암흑광전사[1],암흑고위기사[1],암흑집정관[2]"],
        ["혼종파멸자", "유니크", "토바", "제라툴[1]+짐레이너[1]", "전쟁광[1],저격수[1],망치경호대[2],암흑광전사[1],암흑고위기사[1],암흑집정관[2]"],
        ["보라준", "헬", "토바", "혼종파멸자[2]+혼종약탈자[1]", "전쟁광[3],저격수[3],망치경호대[6],암흑광전사[3],암흑고위기사[3],암흑집정관[6]"],
        ["아르타니스", "레전드", "토바", "보라준[1]+테사다르[1]", "전쟁광[3],저격수[3],망치경호대[6],암흑광전사[4],암흑고위기사[8],암흑집정관[12],원시바퀴[1],변종가시지옥[1],원시히드라리스크[2]"],
        ["라사라", "히든", "토바", "빨정관[1]+광전사석상[3]", "암흑광전사[3],암흑집정관[7]"],
        ["말라쉬", "히든", "토바", "알라라크(XD↑,200%↑)[1]+드라켄레이저천공기(알라라크죽이기)[1]", "전쟁광[1],저격수[1],망치경호대[2],코브라[2],공성파괴단[5],암흑광전사[9],암흑고위기사[13],암흑집정관[6]"],
        ["백인대장", "히든", "토바", "암흑기사(SSS)[2]", "암흑광전사[2],암흑고위기사[2]"],
        ["빨정관", "히든", "토바", "암흑집정관[4]", "암흑집정관[4]"],
        ["승천자", "히든", "토바", "파수병[2]+광전사석상[2]", "암흑광전사[6],암흑고위기사[4],암흑집정관[2]"],
        ["알라라크", "히든", "토바", "피의사냥꾼[2]+혼종파멸자(X↑)[1]", "전쟁광[1],저격수[1],망치경호대[2],암흑광전사[9],암흑고위기사[13],암흑집정관[6]"],
        ["암흑기사", "히든", "토바", "암흑고위기사(SS↑)[1]+암흑광전사(SS↑)[1]", "암흑고위기사[1],암흑광전사[1]"],
        ["카락스", "히든", "토바", "승천자[2]+혼종파멸자(X↑)[1]", "전쟁광[1],저격수[1],망치경호대[2],암흑광전사[13],암흑고위기사[9],암흑집정관[6]"],
        ["탈란다르", "히든", "토바", "카락스(X↑,90%↑)[1]+알라라크(X↑,90%↑)[1]", "전쟁광[2],저격수[2],망치경호대[4],암흑광전사[22],암흑고위기사[22],암흑집정관[12]"],
        ["테사다르", "히든", "토바", "혼종파멸자[1]+정화자사도[4]", "전쟁광[1],저격수[1],망치경호대[2],암흑광전사[1],암흑고위기사[5],암흑집정관[6]"],
        ["파수병", "히든", "토바", "암흑기사(SS)[2]", "암흑광전사[2],암흑고위기사[2]"],
        ["피의사냥꾼", "히든", "토바", "백인대장[2]+정화자사도[2]", "암흑광전사[4],암흑고위기사[6],암흑집정관[2]"],
        ["아몬", "슈퍼히든", "토바", "탈란다르(SXD,300%↑,300킬↑)[1]+아르타니스(SXD,300%↑,300킬↑)[1]+탈다림폭풍함(XD↑)[2]", "전쟁광[5],저격수[5],망치경호대[10],암흑광전사[26],암흑고위기사[30],암흑집정관[40],암흑파수기[8],암흑불멸자[20],원시바퀴[1],변종가시지옥[1],원시히드라리스크[2]"],

        // === [ 토메 ] ===
        ["암흑파수기", "매직", "토메", "", ""],
        ["암흑추적자", "매직", "토메", "", ""],
        ["암흑불멸자", "매직", "토메", "", ""],
        ["선동자", "레어", "토메", "암흑추적자[1]+암흑불멸자[1]", "암흑추적자[1],암흑불멸자[1]"],
        ["교란기", "레어", "토메", "암흑파수기[1]+암흑불멸자[1]", "암흑파수기[1],암흑불멸자[1]"],
        ["거신", "에픽", "토메", "교란기[1]+선동자[1]", "암흑파수기[1],암흑추적자[1],암흑불멸자[2]"],
        ["공허포격기", "유니크", "토메", "대천사[1]+거신[1]", "코브라[1],스파르타중대[1],공성파괴단[2],암흑파수기[1],암흑추적자[1],암흑불멸자[2]"],
        ["분노수호자", "유니크", "토메", "거신[2]", "암흑파수기[2],암흑추적자[2],암흑불멸자[4]"],
        ["공허의구도자", "헬", "토메", "분노수호자[2]+공허포격기[1]", "코브라[1],스파르타중대[1],공성파괴단[2],암흑파수기[5],암흑추적자[5],암흑불멸자[10]"],
        ["셀렌디스", "레전드", "토메", "공허의구도자[1]+정화자거신[1]", "코브라[1],스파르타중대[1],공성파괴단[2],암흑파수기[7],암흑추적자[11],암흑불멸자[18]"],
        ["동력기", "히든", "토메", "암흑파수기(SS↑)[2]", "암흑파수기[2]"],
        ["말살자", "히든", "토메", "암흑불멸자[4]", "암흑불멸자[4]"],
        ["모선핵", "히든", "토메", "차원분광기[1]+공허포격기[1]", "코브라[1],스파르타중대[1],공성파괴단[2],암흑파수기[3],암흑추적자[1],암흑불멸자[6]"],
        ["모한다르", "히든", "토메", "정화자거신(X↑)[1]+공허포격기[4]", "코브라[4],스파르타중대[4],공성파괴단[8],암흑파수기[6],암흑추적자[10],암흑불멸자[16]"],
        ["정화모선", "히든", "토메", "분노수호자[2]+모선핵[1]", "코브라[1],스파르타중대[1],공성파괴단[2],암흑파수기[7],암흑추적자[5],암흑불멸자[14]"],
        ["정화자감시자", "히든", "토메", "정화모선(Lv11,남은강화횟수0회,스킬사용)[3]", "코브라[3],스파르타중대[3],공성파괴단[6],암흑파수기[21],암흑추적자[15],암흑불멸자[42]"],
        ["정화자거신", "히든", "토메", "분노수호자[1]+선동자[4]", "암흑파수기[2],암흑추적자[6],암흑불멸자[8]"],
        ["차원분광기", "히든", "토메", "말살자[1]+동력기[1]", "암흑파수기[2],암흑불멸자[4]"],
        ["케이다린초석", "히든", "토메", "선동자(SSS↑)[9]", "암흑추적자[9],암흑불멸자[9]"],
        ["탈다림모선", "히든", "토메", "정화모선(X↑,90%↑)[1]+탈다림폭풍함(X↑)[1]", "코브라[1],스파르타중대[1],공성파괴단[2],암흑집정관[8],암흑파수기[11],암흑추적자[5],암흑불멸자[24]"],
        ["탈다림폭풍함", "히든", "토메", "폭풍함[2]+빨정관[2]", "암흑집정관[8],암흑파수기[4],암흑불멸자[10]"],
        ["폭풍함", "히든", "토메", "교란기[2]+암흑불멸자[3]", "암흑파수기[2],암흑불멸자[5]"],
        ["하늘군주", "히든", "토메", "셀렌디스(X↑,90%↑)[1]+탈다림폭풍함(X↑)[1]", "코브라[1],스파르타중대[1],공성파괴단[2],암흑집정관[8],암흑파수기[11],암흑추적자[11],암흑불멸자[28]"],
        ["아둔의창", "슈퍼히든", "토메", "셀렌디스(SXD,300%↑,300킬↑)[1]+탈다림모선(SXD,300%↑,300킬↑)[1]+카락스(X↑,150%↑)[2]", "전쟁광[2],저격수[2],망치경호대[4],코브라[2],스파르타중대[2],공성파괴단[4],암흑광전사[26],암흑고위기사[18],암흑집정관[20],암흑파수기[18],암흑추적자[16],암흑불멸자[42]"],

        // === [ 저그중립 ] ===
        ["원시바퀴", "매직", "저그중립", "", ""],
        ["변종가시지옥", "매직", "저그중립", "", ""],
        ["원시히드라리스크", "매직", "저그중립", "", ""],
        ["브루탈리스크", "레어", "저그중립", "변종가시지옥[1]+원시히드라리스크[1]", "변종가시지옥[1],원시히드라리스크[1]"],
        ["라바사우르스", "레어", "저그중립", "원시바퀴[1]+원시히드라리스크[1]", "원시바퀴[1],원시히드라리스크[1]"],
        ["케리건", "에픽", "저그중립", "브루탈리스크[1]+라바사우르스[1]", "원시바퀴[1],변종가시지옥[1],원시히드라리스크[2]"],
        ["혼종약탈자", "유니크", "저그중립", "케리건[1]+제라툴[1]", "암흑광전사[1],암흑고위기사[1],암흑집정관[2],원시바퀴[1],변종가시지옥[1],원시히드라리스크[2]"],
        ["거대괴수", "헬", "저그중립", "혼종약탈자[2]+스투코프[1]", "전쟁광[1],저격수[1],망치경호대[2],암흑광전사[2],암흑고위기사[2],암흑집정관[4],원시바퀴[3],변종가시지옥[3],원시히드라리스크[6]"],
        ["아토실로프", "헬", "저그중립", "우르사돈[암][2]", "우르사돈[암][2]"],
        ["테이스틀로프", "헬", "저그중립", "우르사돈[수][2]", "우르사돈[수][2]"],
        ["원시케리건", "레전드", "저그중립", "거대괴수[1]+크레이스[1]", "전쟁광[1],저격수[1],망치경호대[2],암흑광전사[3],암흑고위기사[3],암흑집정관[6],원시바퀴[4],변종가시지옥[8],원시히드라리스크[12]"],
        ["고름바퀴", "히든", "저그중립", "원시바퀴[3]+암흑추적자[2]", "원시바퀴[3],암흑추적자[2]"],
        ["군단숙주", "히든", "저그중립", "변종가시지옥(SS↑)[2]", "변종가시지옥[2]"],
        ["데하카", "히든", "저그중립", "데하카고치[1]+퀸(SXD)[1]", "전쟁광[7],망치경호대[3],암흑불멸자[4],원시바퀴[3],변종가시지옥[4],원시히드라리스크[3]"],
        ["데하카고치", "히든", "저그중립", "데하카의오른팔[1]+이곤스텟먼(SXD)[1]", "전쟁광[7],망치경호대[3],암흑불멸자[4],원시바퀴[2],원시히드라리스크[2]"],
        ["데하카의오른팔", "히든", "저그중립", "100라운드이전까지저그업20↑ [(타 종족 업 0)[1],역전 복권10회[1],인생 복권3회시-소환[1]]", "없음"],
        ["땅굴파괴자", "히든", "저그중립", "아토실로프(X↑,200%↑,Lv7)[4]", "우르사돈[암][8]"],
        ["무리군주", "히든", "저그중립", "퀸[2]+크레이스[1]", "암흑광전사[1],암흑고위기사[1],암흑집정관[2],원시바퀴[3],변종가시지옥[13],원시히드라리스크[8]"],
        ["살모사", "히든", "저그중립", "퀸[1]+일벌레(SS↑)[3]", "원시바퀴[2],변종가시지옥[4],원시히드라리스크[3]"],
        ["수호군주", "히든", "저그중립", "살모사(X↑)[1]+군단숙주(잠복)[2]", "원시바퀴[2],변종가시지옥[8],원시히드라리스크[3]"],
        ["아포칼리스크", "히든", "저그중립", "오메가리스크(X↑,90%↑,100킬↑)[2]+오딘(10킬↑)[1]", "스파르타중대[2],코브라[2],공성파괴단[4],암흑광전사[4],암흑고위기사[4],암흑집정관[8],원시바퀴[10],변종가시지옥[10],원시히드라리스크[20]"],
        ["알렉산더", "히든", "저그중립", "포식귀[1]+수호군주[1]+히페리온(풀강화)[1]+스투코프(SXD)[1]", "전쟁광[1],저격수[1],망치경호대[2],스파르타중대[5],코브라[5],공성파괴단[10],암흑파수기[1],암흑추적자[3],암흑불멸자[2],원시바퀴[8],변종가시지옥[13],원시히드라리스크[8]"],
        ["오메가리스크", "히든", "저그중립", "혼종약탈자[2]+케리건[3]", "암흑광전사[2],암흑고위기사[2],암흑집정관[4],원시바퀴[5],변종가시지옥[5],원시히드라리스크[10]"],
        ["일벌레", "히든", "저그중립", "원시바퀴(잠복)[1]+원시히드라리스크(잠복)[2]", "원시바퀴[1],원시히드라리스크[2]"],
        ["크레이스", "히든", "저그중립", "혼종약탈자[1]+브루탈리스크[4]", "암흑광전사[1],암흑고위기사[1],암흑집정관[2],원시바퀴[1],변종가시지옥[5],원시히드라리스크[6]"],
        ["토라스크", "히든", "저그중립", "오메가리스크(X↑,90%↑)[1]+고름바퀴[2]", "암흑광전사[2],암흑고위기사[2],암흑집정관[4],암흑추적자[4],원시바퀴[11],변종가시지옥[5],원시히드라리스크[10]"],
        ["포식귀", "히든", "저그중립", "살모사[1]+고름바퀴(X↑)[1]", "암흑추적자[2],원시바퀴[5],변종가시지옥[4],원시히드라리스크[3]"],
        ["포자주둥이", "히든", "저그중립", "일벌레(미니성큰스킬사용,히든성소배치)SSS↑)[12]", "원시바퀴[8],원시히드라리스크[4]"],
        ["퀸", "히든", "저그중립", "군단숙주[2]+라바사우르스[1]", "원시바퀴[1],변종가시지옥[4],원시히드라리스크[1]"],
        ["하이브리드로프", "히든", "저그중립", "아토실로프(Lv7)[1]+테이스틀로프(Lv7)[1]", "우르사돈[암][2],우르사돈[수][2]"],
        ["불새케리건", "슈퍼히든", "저그중립", "원시케리건(SXD,300%↑,300킬↑)[1]+토라스크(SXD,300%↑,300킬↑)[1]+낮까마귀(X↑,150%↑)[2]", "시체매-지뢰매설[48],전쟁광[1],저격수[1],망치경호대[2],코브라[6],스파르타중대[12],암흑광전사[9],암흑고위기사[5],암흑집정관[10],암흑추적자[4],원시바퀴[15],변종가시지옥[13],원시히드라리스크[22]"],
        ["초월체", "슈퍼히든", "저그중립", "하이브리드로프(SXD↑,300%↑,Lv7)[2]+테사다르(XD↑)[1]+크레이스(XD↑)[1]+과학선(XD↑)[1]+정화자거신(XD↑)[1]+워필드장군(XD↑)[1]", "전쟁광[2],저격수[6],망치경호대[8],코브라[6],스파르타중대[2],공성파괴단[8],암흑광전사[2],암흑고위기사[6],암흑집정관[8],암흑파수기[2],암흑추적자[6],암흑불멸자[8],원시바퀴[2],변종가시지옥[6],원시히드라리스크[8],우르사돈[암][4],우르사돈[수][4]"],

        // === [ 혼종 ] ===
        ["공허분쇄자", "히든", "혼종", "혼종네메시스(XD↑,200%↑,11Lv)[1]+파멸자(XD↑,200%↑,11Lv)[1]", "전쟁광[2],저격수[2],망치경호대[4],암흑광전사[3],암흑고위기사[11],암흑집정관[14],원시바퀴[3],변종가시지옥[13],원시히드라리스크[8]"],
        ["사라케리건", "히든", "혼종", "노바(X↑,90%↑)[1]+원시케리건(X↑,90%↑)[1]", "전쟁광[4],저격수[4],망치경호대[8],암흑광전사[4],암흑고위기사[4],암흑집정관[8],원시바퀴[6],변종가시지옥[10],원시히드라리스크[16]"],
        ["아몬의젤나가피조물", "히든", "혼종", "젤나가피조물(RXD)[1]+파멸자(XD↑)[1]", "시체매-지뢰매설[8],전쟁광[1],저격수[1],망치경호대[2],코브라[17],스파르타중대[16],공성파괴단[24],암흑광전사[15],암흑고위기사[9],암흑집정관[6],암흑파수기[12],암흑추적자[20],암흑불멸자[32]"],
        ["유물", "히든", "혼종", "유물조각[5]", "유물조각[5]"],
        ["젤나가피조물", "히든", "혼종", "카락스(XD↑)[1]+모한다르(X↑)[1]", "전쟁광[1],저격수[1],망치경호대[2],코브라[4],스파르타중대[4],공성파괴단[8],암흑광전사[13],암흑고위기사[9],암흑집정관[6],암흑파수기[6],암흑추적자[10],암흑불멸자[16]"],
        ["티라노조르", "히든", "혼종", "토라스크(XD↑)[1]+테이스틀로프(X↑)[2]", "암흑광전사[2],암흑고위기사[2],암흑집정관[4],암흑추적자[4],원시바퀴[11],변종가시지옥[5],원시히드라리스크[10],우르사돈[수][4]"],
        ["파멸자", "히든", "혼종", "모한다르(X↑,90%↑)[1]+폭격기(X↑,90%↑)[1]", "시체매-지뢰매설[24],코브라[13],스파르타중대[12],공성파괴단[16],암흑광전사[2],암흑파수기[6],암흑추적자[10],암흑불멸자[14]"],
        ["혼종네메시스", "히든", "혼종", "무리군주(X↑,90%↑)[1]+테사다르(X↑)[2]", "전쟁광[1],저격수[1],망치경호대[2],암흑광전사[2],암흑고위기사[6],암흑집정관[8],원시바퀴[3],변종가시지옥[13],원시히드라리스크[8]"],
        ["혼종뫼비우스", "히든", "혼종", "해적주력함(X↑,한계돌파3↑)[1]+탈다림모선(X↑,한계돌파3↑)[1]+갓오브타임(스킬사용)[1]", "코브라[14],스파르타중대[14],공성파괴단[28],암흑집정관[8],암흑파수기[12],암흑추적자[6],암흑불멸자[26],갓오브타임[1]"],
        ["혼종베히모스", "히든", "혼종", "알라라크(X↑,90%↑)[1]+워필드장군(X↑)[2]", "전쟁광[3],저격수[11],망치경호대[14],암흑고위기사[13],암흑광전사[9],암흑집정관[6],원시바퀴[2],변종가시지옥[2],원시히드라리스크[4]"],
        ["혼종종언자", "히든", "혼종", "사라케리건(XD↑,200%↑,Lv11)[1]+혼종베히모스(XD↑,200%↑,Lv11)[1]", "전쟁광[7],저격수[15],망치경호대[22],암흑광전사[13],암흑고위기사[17],암흑집정관[14],원시바퀴[8],변종가시지옥[12],원시히드라리스크[20]"],
        ["나루드", "슈퍼히든", "혼종", "공허분쇄자(SXD,300%↑,300~999kill)[2]+사라케리건(X↑,150%↑)[2]", "전쟁광[12],저격수[12],망치경호대[24],코브라[26],스파르타중대[24],공성파괴단[32],암흑광전사[18],암흑고위기사[30],암흑집정관[44],암흑파수기[12],암흑추적자[20],암흑불멸자[32],원시바퀴[18],변종가시지옥[46],원시히드라리스크[48],시체매-지뢰매설[48]"]
    ],
    en: [
        // === [ T-Bio ] ===
        ["Warmonger", "Magic", "T-Bio", "", ""],
        ["Sniper", "Magic", "T-Bio", "", ""],
        ["Hammer Securities", "Magic", "T-Bio", "", ""],
        ["Death Head", "Rare", "T-Bio", "Warmonger[1]+Hammer Securities[1]", "Warmonger[1],Hammer Securities[1]"],
        ["Spectre", "Rare", "T-Bio", "Sniper[1]+Hammer Securities[1]", "Sniper[1],Hammer Securities[1]"],
        ["Jim Raynor", "Epic", "T-Bio", "Death Head[1]+Spectre[1]", "Warmonger[1],Sniper[1],Hammer Securities[2]"],
        ["Stukov", "Unique", "T-Bio", "Jim Raynor[1]+Kerrigan[1]", "Warmonger[1],Sniper[1],Hammer Securities[2],Primal Roach[1],Primal Lurker[1],Primal Hydralisk[2]"],
        ["Nova", "Hell", "T-Bio", "Stukov[2]+Hybrid Dominator[1]", "Warmonger[3],Sniper[3],Hammer Securities[6],Primal Roach[2],Primal Lurker[2],Primal Hydralisk[4]"],
        ["Commando Raynor", "Legend", "T-Bio", "Nova[1]+General Warfield[1]", "Warmonger[4],Sniper[8],Hammer Securities[12],Dark Zealot[1],Dark High Templar[1],Dark Archon[2],Primal Roach[3],Primal Lurker[3],Primal Hydralisk[6]"],
        ["Tosh", "Hidden", "T-Bio", "Spectre[2]+Hammer Securities[3]", "Sniper[2],Hammer Securities[5]"],
        ["Miner", "Hidden", "T-Bio", "Helper(500kills+)[1]+Tauren Toilet[1]", "Warmonger[4],Dark Immortal[4],Helper[1]"],
        ["Swan", "Hidden", "T-Bio", "Dominion Marauder[2]+Raven[1]+Auto Turret[1]", "Warmonger[8],Hammer Securities[6],Raven[1],Auto Turret[5]"],
        ["Miles Blaze Lewis", "Hidden", "T-Bio", "Prometheus Company(X,90%+)+Dominion Marauder[2]+Crimson Archon(10kills+)[1]", "Dark Archon[4],Warmonger[8],Sniper[4],Hammer Securities[10],Spartan Company[4]"],
        ["Murloc Marine", "Hidden", "T-Bio", "Death Head[3]+Ravasaur(Burrow)[2]", "Warmonger[3],Hammer Securities[3],Primal Roach[2],Primal Hydralisk[2]"],
        ["General Warfield", "Hidden", "T-Bio", "Stukov[1]+Spectre[4]", "Warmonger[1],Sniper[5],Hammer Securities[6],Primal Roach[1],Primal Lurker[1],Primal Hydralisk[2]"],
        ["Stetman", "Hidden", "T-Bio", "Murloc Marine[1]+Tauren Toilet[1]", "Warmonger[7],Hammer Securities[3],Dark Immortal[4],Primal Roach[2],Primal Hydralisk[2]"],
        ["Dominion Marauder", "Hidden", "T-Bio", "Tauren Space Marine[2]+Hammer Securities[3]", "Warmonger[4],Hammer Securities[3]"],
        ["Tauren Space Marine", "Hidden", "T-Bio", "Warmonger(SS+)[2]", "Warmonger[2]"],
        ["Tauren Toilet", "Hidden", "T-Bio", "Tauren Space Marine[2]+Annihilator[1]", "Warmonger[4],Dark Immortal[4]"],
        ["Tychus Findlay", "Hidden", "T-Bio", "Swan(X+)[1]+Stetman(X+)[1]", "Warmonger[15],Hammer Securities[9],Dark Immortal[4],Primal Roach[2],Primal Hydralisk[2],Auto Turret[5]"],
        ["Prometheus Company", "Hidden", "T-Bio", "Tosh(SSS+)[2]+Spartan Company[4]", "Sniper[4],Hammer Securities[10],Spartan Company[4]"],
        ["Special Ops Nova", "SuperHidden", "T-Bio", "Commando Raynor(SXD,300%+,300kills+)[1]+Tychus Findlay(SXD,300%+,300kills+)[1]+Omegalisk(X+,150%+)[2]", "Warmonger[19],Sniper[8],Hammer Securities[21],Dark Zealot[5],Dark High Templar[5],Dark Archon[10],Primal Roach[15],Primal Lurker[13],Primal Hydralisk[28],Auto Turret[5]"],

        // === [ T-Mech ] ===
        ["Spartan Company", "Magic", "T-Mech", "", ""],
        ["Diamondback", "Magic", "T-Mech", "", ""],
        ["Siege Breaker", "Magic", "T-Mech", "", ""],
        ["Blackhammer", "Rare", "T-Mech", "Spartan Company[1]+Siege Breaker[1]", "Spartan Company[1],Siege Breaker[1]"],
        ["ARES", "Rare", "T-Mech", "Diamondback[1]+Siege Breaker[1]", "Diamondback[1],Siege Breaker[1]"],
        ["Archangel", "Epic", "T-Mech", "Blackhammer[1]+ARES[1]", "Diamondback[1],Spartan Company[1],Siege Breaker[2]"],
        ["Odin", "Unique", "T-Mech", "Archangel[2]", "Diamondback[2],Spartan Company[2],Siege Breaker[4]"],
        ["Hyperion", "Hell", "T-Mech", "Odin[2]+Void Ray[1]", "Diamondback[5],Spartan Company[5],Siege Breaker[10],Dark Sentry[1],Dark Stalker[1],Dark Immortal[2]"],
        ["Gorgon Battlecruiser", "Legend", "T-Mech", "Hyperion[1]+Science Vessel[1]", "Diamondback[11],Spartan Company[7],Siege Breaker[18],Dark Sentry[1],Dark Stalker[1],Dark Immortal[2]"],
        ["Science Vessel", "Hidden", "T-Mech", "Odin[1]+ARES[4]", "Diamondback[6],Spartan Company[2],Siege Breaker[8]"],
        ["Raven", "Hidden", "T-Mech", "Widow Mine[2]+WarHound[3]+Garbage[1]", "Vulture-MinePlant[24],Diamondback[3],Spartan Company[6],Dark Zealot[2]"],
        // [수정완료] Sky Fury(창공의 분노) 영어 조합식 Limit Break 1+ 로 변경
        ["Arch Fighter", "Hidden", "T-Mech", "Archangel(SSS+)[4]", "Diamondback[4],Spartan Company[4],Siege Breaker[8]"],
        ["Drakken Laser Drill", "Hidden", "T-Mech", "Siege Breaker[3]+ARES[2]", "Diamondback[2],Siege Breaker[5]"],
        ["Widow Mine", "Hidden", "T-Mech", "Spider Mine (Planted by Vulture)[12]", "Vulture-MinePlant[12]"],
        ["Pride of Augustgrad", "Hidden", "T-Mech", "Gorgon Battlecruiser(0 Upgrades Left,1000kills)[1]+Blackhammer(SSS)[4]", "Diamondback[11],Spartan Company[11],Siege Breaker[22],Dark Sentry[1],Dark Stalker[1],Dark Immortal[2]"],
        ["Zeus Lander", "Hidden", "T-Mech", "Pirate Capital Ship(Lv11)[1]+Hercules Bomber(Lv11)[1]+Massive Disaster (Skill Used)[1]", "Spartan Company[21],Diamondback[22],Siege Breaker[34],Dark Zealot[2],Dark Sentry[1],Dark Stalker[1],Dark Immortal[2],Vulture-MinePlant[24],Massive Disaster[1]"],
        ["Sky Fury", "Hidden", "T-Mech", "Arch Fighter(Limit Break 1+,500kills+)[1]+Wrathwalker(X+)[1]", "Diamondback[4],Spartan Company[4],Siege Breaker[8],Dark Sentry[2],Dark Stalker[2],Dark Immortal[4]"],
        ["Garbage", "Hidden", "T-Mech", "Diamondback[3]+Dark Zealot[2]", "Diamondback[3],Dark Zealot[2]"],
        ["WarHound", "Hidden", "T-Mech", "Spartan Company(SS+)[2]", "Spartan Company[2]"],
        ["Hercules Bomber", "Hidden", "T-Mech", "Raven(X+)[1]+Science Vessel(X+)[1]", "Vulture-MinePlant[24],Diamondback[9],Spartan Company[8],Siege Breaker[8],Dark Zealot[2]"],
        ["NUKE SYSTEM", "Hidden", "T-Mech", "Tauren Toilet[1]+Garbage[2]+Crimson Archon[1]", "Warmonger[4],Diamondback[6],Dark Zealot[4],Dark Archon[4],Dark Immortal[4]"],
        ["Pirate Capital Ship", "Hidden", "T-Mech", "Arch Fighter[2]+Hyperion(X+,90%+)[1]", "Diamondback[13],Spartan Company[13],Siege Breaker[26],Dark Sentry[1],Dark Stalker[1],Dark Immortal[2]"],
        ["Terratron", "SuperHidden", "T-Mech", "Gorgon Battlecruiser(SXD,300%+,300kills+)[1]+Pirate Capital Ship(SXD,300%+,300kills+)[1]+Swan(XD+)[2]", "Warmonger[16],Hammer Securities[12],Diamondback[24],Spartan Company[20],Siege Breaker[44],Dark Sentry[2],Dark Stalker[2],Dark Immortal[4],Auto Turret[10]"],

        // === [ P-Bio ] ===
        ["Dark Zealot", "Magic", "P-Bio", "", ""],
        ["Dark High Templar", "Magic", "P-Bio", "", ""],
        ["Dark Archon", "Magic", "P-Bio", "", ""],
        ["Stone Zealot", "Rare", "P-Bio", "Dark Zealot[1]+Dark Archon[1]", "Dark Zealot[1],Dark Archon[1]"],
        ["Purifier Adept", "Rare", "P-Bio", "Dark High Templar[1]+Dark Archon[1]", "Dark High Templar[1],Dark Archon[1]"],
        ["Zeratul", "Epic", "P-Bio", "Stone Zealot[1]+Purifier Adept[1]", "Dark Zealot[1],Dark High Templar[1],Dark Archon[2]"],
        ["Hybrid Dominator", "Unique", "P-Bio", "Zeratul[1]+Jim Raynor[1]", "Warmonger[1],Sniper[1],Hammer Securities[2],Dark Zealot[1],Dark High Templar[1],Dark Archon[2]"],
        ["Vorazun", "Hell", "P-Bio", "Hybrid Dominator[2]+Hybrid Reaver[1]", "Warmonger[3],Sniper[3],Hammer Securities[6],Dark Zealot[3],Dark High Templar[3],Dark Archon[6]"],
        ["Artanis", "Legend", "P-Bio", "Vorazun[1]+Tassadar[1]", "Warmonger[3],Sniper[3],Hammer Securities[6],Dark Zealot[4],Dark High Templar[8],Dark Archon[12],Primal Roach[1],Primal Lurker[1],Primal Hydralisk[2]"],
        ["Lasarra", "Hidden", "P-Bio", "Crimson Archon[1]+Stone Zealot[3]", "Dark Zealot[3],Dark Archon[7]"],
        ["Malash", "Hidden", "P-Bio", "Alarak(XD+,200%+)[1]+Drakken Laser Drill (Kill Alarak)[1]", "Warmonger[1],Sniper[1],Hammer Securities[2],Diamondback[2],Siege Breaker[5],Dark Zealot[9],Dark High Templar[13],Dark Archon[6]"],
        ["Centurion", "Hidden", "P-Bio", "Dark Templar(SSS)[2]", "Dark Zealot[2],Dark High Templar[2]"],
        ["Crimson Archon", "Hidden", "P-Bio", "Dark Archon[4]", "Dark Archon[4]"],
        ["Ascendant", "Hidden", "P-Bio", "Sentinel[2]+Stone Zealot[2]", "Dark Zealot[6],Dark High Templar[4],Dark Archon[2]"],
        ["Alarak", "Hidden", "P-Bio", "Blood Hunter[2]+Hybrid Dominator(X+)[1]", "Warmonger[1],Sniper[1],Hammer Securities[2],Dark Zealot[9],Dark High Templar[13],Dark Archon[6]"],
        ["Dark Templar", "Hidden", "P-Bio", "Dark High Templar(SS+)[1]+Dark Zealot(SS+)[1]", "Dark High Templar[1],Dark Zealot[1]"],
        ["Karax", "Hidden", "P-Bio", "Ascendant[2]+Hybrid Dominator(X+)[1]", "Warmonger[1],Sniper[1],Hammer Securities[2],Dark Zealot[13],Dark High Templar[9],Dark Archon[6]"],
        ["Talandar", "Hidden", "P-Bio", "Karax(X+,90%+)[1]+Alarak(X+,90%+)[1]", "Warmonger[2],Sniper[2],Hammer Securities[4],Dark Zealot[22],Dark High Templar[22],Dark Archon[12]"],
        ["Tassadar", "Hidden", "P-Bio", "Hybrid Dominator[1]+Purifier Adept[4]", "Warmonger[1],Sniper[1],Hammer Securities[2],Dark Zealot[1],Dark High Templar[5],Dark Archon[6]"],
        ["Sentinel", "Hidden", "P-Bio", "Dark Templar(SS)[2]", "Dark Zealot[2],Dark High Templar[2]"],
        ["Blood Hunter", "Hidden", "P-Bio", "Centurion[2]+Purifier Adept[2]", "Dark Zealot[4],Dark High Templar[6],Dark Archon[2]"],
        ["Amon", "SuperHidden", "P-Bio", "Talandar(SXD,300%+,300kills+)[1]+Artanis(SXD,300%+,300kills+)[1]+Tal'Darim Tempest(XD+)[2]", "Warmonger[5],Sniper[5],Hammer Securities[10],Dark Zealot[26],Dark High Templar[30],Dark Archon[40],Dark Sentry[8],Dark Immortal[20],Primal Roach[1],Primal Lurker[1],Primal Hydralisk[2]"],

        // === [ P-Mech ] ===
        ["Dark Sentry", "Magic", "P-Mech", "", ""],
        ["Dark Stalker", "Magic", "P-Mech", "", ""],
        ["Dark Immortal", "Magic", "P-Mech", "", ""],
        ["Instigator", "Rare", "P-Mech", "Dark Stalker[1]+Dark Immortal[1]", "Dark Stalker[1],Dark Immortal[1]"],
        ["Havoc", "Rare", "P-Mech", "Dark Sentry[1]+Dark Immortal[1]", "Dark Sentry[1],Dark Immortal[1]"],
        ["Colossus", "Epic", "P-Mech", "Havoc[1]+Instigator[1]", "Dark Sentry[1],Dark Stalker[1],Dark Immortal[2]"],
        ["Void Ray", "Unique", "P-Mech", "Archangel[1]+Colossus[1]", "Diamondback[1],Spartan Company[1],Siege Breaker[2],Dark Sentry[1],Dark Stalker[1],Dark Immortal[2]"],
        ["Wrathwalker", "Unique", "P-Mech", "Colossus[2]", "Dark Sentry[2],Dark Stalker[2],Dark Immortal[4]"],
        ["Void Seeker", "Hell", "P-Mech", "Wrathwalker[2]+Void Ray[1]", "Diamondback[1],Spartan Company[1],Siege Breaker[2],Dark Sentry[5],Dark Stalker[5],Dark Immortal[10]"],
        ["Selendis", "Legend", "P-Mech", "Void Seeker[1]+Purifier Colossus[1]", "Diamondback[1],Spartan Company[1],Siege Breaker[2],Dark Sentry[7],Dark Stalker[11],Dark Immortal[18]"],
        ["Energizer", "Hidden", "P-Mech", "Dark Sentry(SS+)[2]", "Dark Sentry[2]"],
        ["Annihilator", "Hidden", "P-Mech", "Dark Immortal[4]", "Dark Immortal[4]"],
        ["Mothership Core", "Hidden", "P-Mech", "Warp Prism[1]+Void Ray[1]", "Diamondback[1],Spartan Company[1],Siege Breaker[2],Dark Sentry[3],Dark Stalker[1],Dark Immortal[6]"],
        ["Mohandar", "Hidden", "P-Mech", "Purifier Colossus(X+)[1]+Void Ray[4]", "Diamondback[4],Spartan Company[4],Siege Breaker[8],Dark Sentry[6],Dark Stalker[10],Dark Immortal[16]"],
        ["MotherShip", "Hidden", "P-Mech", "Wrathwalker[2]+Mothership Core[1]", "Diamondback[1],Spartan Company[1],Siege Breaker[2],Dark Sentry[7],Dark Stalker[5],Dark Immortal[14]"],
        ["Purifier Warden", "Hidden", "P-Mech", "MotherShip(Lv11,0 Upgrades Left,Skill Used)[3]", "Diamondback[3],Spartan Company[3],Siege Breaker[6],Dark Sentry[21],Dark Stalker[15],Dark Immortal[42]"],
        ["Purifier Colossus", "Hidden", "P-Mech", "Wrathwalker[1]+Instigator[4]", "Dark Sentry[2],Dark Stalker[6],Dark Immortal[8]"],
        ["Warp Prism", "Hidden", "P-Mech", "Annihilator[1]+Energizer[1]", "Dark Sentry[2],Dark Immortal[4]"],
        ["Khaydarin Monolith", "Hidden", "P-Mech", "Instigator(SSS+)[9]", "Dark Stalker[9],Dark Immortal[9]"],
        ["Tal'Darim Mothership", "Hidden", "P-Mech", "MotherShip(X+,90%+)[1]+Tal'Darim Tempest(X+)[1]", "Diamondback[1],Spartan Company[1],Siege Breaker[2],Dark Archon[8],Dark Sentry[11],Dark Stalker[5],Dark Immortal[24]"],
        ["Tal'Darim Tempest", "Hidden", "P-Mech", "Tempest[2]+Crimson Archon[2]", "Dark Archon[8],Dark Sentry[4],Dark Immortal[10]"],
        ["Tempest", "Hidden", "P-Mech", "Havoc[2]+Dark Immortal[3]", "Dark Sentry[2],Dark Immortal[5]"],
        ["Skylord", "Hidden", "P-Mech", "Selendis(X+,90%+)[1]+Tal'Darim Tempest(X+)[1]", "Diamondback[1],Spartan Company[1],Siege Breaker[2],Dark Archon[8],Dark Sentry[11],Dark Stalker[11],Dark Immortal[28]"],
        ["Spear of Adun", "SuperHidden", "P-Mech", "Selendis(SXD,300%+,300kills+)[1]+Tal'Darim Mothership(SXD,300%+,300kills+)[1]+Karax(X+,150%+)[2]", "Warmonger[2],Sniper[2],Hammer Securities[4],Diamondback[2],Spartan Company[2],Siege Breaker[4],Dark Zealot[26],Dark High Templar[18],Dark Archon[20],Dark Sentry[18],Dark Stalker[16],Dark Immortal[42]"],

        // === [ Zerg/Neutral ] ===
        ["Primal Roach", "Magic", "Zerg/Neutral", "", ""],
        ["Primal Lurker", "Magic", "Zerg/Neutral", "", ""],
        ["Primal Hydralisk", "Magic", "Zerg/Neutral", "", ""],
        ["Brutalisk", "Rare", "Zerg/Neutral", "Primal Lurker[1]+Primal Hydralisk[1]", "Primal Lurker[1],Primal Hydralisk[1]"],
        ["Ravasaur", "Rare", "Zerg/Neutral", "Primal Roach[1]+Primal Hydralisk[1]", "Primal Roach[1],Primal Hydralisk[1]"],
        ["Kerrigan", "Epic", "Zerg/Neutral", "Brutalisk[1]+Ravasaur[1]", "Primal Roach[1],Primal Lurker[1],Primal Hydralisk[2]"],
        ["Hybrid Reaver", "Unique", "Zerg/Neutral", "Kerrigan[1]+Zeratul[1]", "Dark Zealot[1],Dark High Templar[1],Dark Archon[2],Primal Roach[1],Primal Lurker[1],Primal Hydralisk[2]"],
        ["Leviathan", "Hell", "Zerg/Neutral", "Hybrid Reaver[2]+Stukov[1]", "Warmonger[1],Sniper[1],Hammer Securities[2],Dark Zealot[2],Dark High Templar[2],Dark Archon[4],Primal Roach[3],Primal Lurker[3],Primal Hydralisk[6]"],
        ["Atosilope", "Hell", "Zerg/Neutral", "Yeti(F)[2]", "Yeti(F)[2]"],
        ["Tastelope", "Hell", "Zerg/Neutral", "Yeti(M)[2]", "Yeti(M)[2]"],
        ["K5 Kerrigan", "Legend", "Zerg/Neutral", "Leviathan[1]+Kraith[1]", "Warmonger[1],Sniper[1],Hammer Securities[2],Dark Zealot[3],Dark High Templar[3],Dark Archon[6],Primal Roach[4],Primal Lurker[8],Primal Hydralisk[12]"],
        ["Vile Roach", "Hidden", "Zerg/Neutral", "Primal Roach[3]+Dark Stalker[2]", "Primal Roach[3],Dark Stalker[2]"],
        ["Swarm Host", "Hidden", "Zerg/Neutral", "Primal Lurker(SS+)[2]", "Primal Lurker[2]"],
        ["Dehaka", "Hidden", "Zerg/Neutral", "Dehaka's Cocoon[1]+Queen(SXD)[1]", "Warmonger[7],Hammer Securities[3],Dark Immortal[4],Primal Roach[3],Primal Lurker[4],Primal Hydralisk[3]"],
        ["Dehaka's Cocoon", "Hidden", "Zerg/Neutral", "Dehaka's Right Arm[1]+Stetman(SXD)[1]", "Warmonger[7],Hammer Securities[3],Dark Immortal[4],Primal Roach[2],Primal Hydralisk[2]"],
        ["Dehaka's Right Arm", "Hidden", "Zerg/Neutral", "Zerg Up 20+ before Round 100 [(Other Race Up 0)[1], Reversal Lottery 10 times[1], Life Lottery 3 times-Summon[1]]", "None"],
        ["Nydus Destroyer", "Hidden", "Zerg/Neutral", "Atosilope(X+,200%+,Lv7)[4]", "Yeti(F)[8]"],
        ["Brood Lord", "Hidden", "Zerg/Neutral", "Queen[2]+Kraith[1]", "Dark Zealot[1],Dark High Templar[1],Dark Archon[2],Primal Roach[3],Primal Lurker[13],Primal Hydralisk[8]"],
        ["Viper", "Hidden", "Zerg/Neutral", "Queen[1]+Drone(SS+)[3]", "Primal Roach[2],Primal Lurker[4],Primal Hydralisk[3]"],
        ["Guardian", "Hidden", "Zerg/Neutral", "Viper(X+)[1]+Swarm Host(Burrow)[2]", "Primal Roach[2],Primal Lurker[8],Primal Hydralisk[3]"],
        ["Apocalisk", "Hidden", "Zerg/Neutral", "Omegalisk(X+,90%+,100kills+)[2]+Odin(10kills+)[1]", "Spartan Company[2],Diamondback[2],Siege Breaker[4],Dark Zealot[4],Dark High Templar[4],Dark Archon[8],Primal Roach[10],Primal Lurker[10],Primal Hydralisk[20]"],
        ["Aleksander", "Hidden", "Zerg/Neutral", "Devourer[1]+Guardian[1]+Hyperion(Fully Upgraded)[1]+Stukov(SXD)[1]", "Warmonger[1],Sniper[1],Hammer Securities[2],Spartan Company[5],Diamondback[5],Siege Breaker[10],Dark Sentry[1],Dark Stalker[3],Dark Immortal[2],Primal Roach[8],Primal Lurker[13],Primal Hydralisk[8]"],
        ["Omegalisk", "Hidden", "Zerg/Neutral", "Hybrid Reaver[2]+Kerrigan[3]", "Dark Zealot[2],Dark High Templar[2],Dark Archon[4],Primal Roach[5],Primal Lurker[5],Primal Hydralisk[10]"],
        ["Drone", "Hidden", "Zerg/Neutral", "Primal Roach(Burrow)[1]+Primal Hydralisk(Burrow)[2]", "Primal Roach[1],Primal Hydralisk[2]"],
        ["Kraith", "Hidden", "Zerg/Neutral", "Hybrid Reaver[1]+Brutalisk[4]", "Dark Zealot[1],Dark High Templar[1],Dark Archon[2],Primal Roach[1],Primal Lurker[5],Primal Hydralisk[6]"],
        ["Torrasque", "Hidden", "Zerg/Neutral", "Omegalisk(X+,90%+)[1]+Vile Roach[2]", "Dark Zealot[2],Dark High Templar[2],Dark Archon[4],Dark Stalker[4],Primal Roach[11],Primal Lurker[5],Primal Hydralisk[10]"],
        ["Devourer", "Hidden", "Zerg/Neutral", "Viper[1]+Vile Roach(X+)[1]", "Dark Stalker[2],Primal Roach[5],Primal Lurker[4],Primal Hydralisk[3]"],
        ["Spore Cannon", "Hidden", "Zerg/Neutral", "Drone(Mini Sunken Skill Used,Hidden Shrine Placed,SSS+)[12]", "Primal Roach[8],Primal Hydralisk[4]"],
        ["Queen", "Hidden", "Zerg/Neutral", "Swarm Host[2]+Ravasaur[1]", "Primal Roach[1],Primal Lurker[4],Primal Hydralisk[1]"],
        ["Hybridlope", "Hidden", "Zerg/Neutral", "Atosilope(Lv7)[1]+Tastelope(Lv7)[1]", "Yeti(F)[2],Yeti(M)[2]"],
        ["Xel'Naga Kerrigan", "SuperHidden", "Zerg/Neutral", "K5 Kerrigan(SXD,300%+,300kills+)[1]+Torrasque(SXD,300%+,300kills+)[1]+Raven(X+,150%+)[2]", "Vulture-MinePlant[48],Warmonger[1],Sniper[1],Hammer Securities[2],Diamondback[6],Spartan Company[12],Dark Zealot[9],Dark High Templar[5],Dark Archon[10],Dark Stalker[4],Primal Roach[15],Primal Lurker[13],Primal Hydralisk[22]"],
        ["Overmind", "SuperHidden", "Zerg/Neutral", "Hybridlope(SXD+,300%+,Lv7)[2]+Tassadar(XD+)[1]+Kraith(XD+)[1]+Science Vessel(XD+)[1]+Purifier Colossus(XD+)[1]+General Warfield(XD+)[1]", "Warmonger[2],Sniper[6],Hammer Securities[8],Diamondback[6],Spartan Company[2],Siege Breaker[8],Dark Zealot[2],Dark High Templar[6],Dark Archon[8],Dark Sentry[2],Dark Stalker[6],Dark Immortal[8],Primal Roach[2],Primal Lurker[6],Primal Hydralisk[8],Yeti(F)[4],Yeti(M)[4]"],

        // === [ Hybrid ] ===
        ["Void Thrasher", "Hidden", "Hybrid", "Hybrid Nemesis(XD+,200%+,Lv11)[1]+Destroyer(XD+,200%+,Lv11)[1]", "Warmonger[2],Sniper[2],Hammer Securities[4],Dark Zealot[3],Dark High Templar[11],Dark Archon[14],Primal Roach[3],Primal Lurker[13],Primal Hydralisk[8]"],
        ["Sarah Kerrigan", "Hidden", "Hybrid", "Nova(X+,90%+)[1]+K5 Kerrigan(X+,90%+)[1]", "Warmonger[4],Sniper[4],Hammer Securities[8],Dark Zealot[4],Dark High Templar[4],Dark Archon[8],Primal Roach[6],Primal Lurker[10],Primal Hydralisk[16]"],
        ["Amon's Xel'Naga Construct", "Hidden", "Hybrid", "Xel'Naga Construct(RXD)[1]+Destroyer(XD+)[1]", "Vulture-MinePlant[8],Warmonger[1],Sniper[1],Hammer Securities[2],Diamondback[17],Spartan Company[16],Siege Breaker[24],Dark Zealot[15],Dark High Templar[9],Dark Archon[6],Dark Sentry[12],Dark Stalker[20],Dark Immortal[32]"],
        ["Artifact", "Hidden", "Hybrid", "Artifact Fragment[5]", "Artifact Fragment[5]"],
        ["Xel'Naga Construct", "Hidden", "Hybrid", "Karax(XD+)[1]+Mohandar(X+)[1]", "Warmonger[1],Sniper[1],Hammer Securities[2],Diamondback[4],Spartan Company[4],Siege Breaker[8],Dark Zealot[13],Dark High Templar[9],Dark Archon[6],Dark Sentry[6],Dark Stalker[10],Dark Immortal[16]"],
        ["Tyrannozor", "Hidden", "Hybrid", "Torrasque(XD+)[1]+Tastelope(X+)[2]", "Dark Zealot[2],Dark High Templar[2],Dark Archon[4],Dark Stalker[4],Primal Roach[11],Primal Lurker[5],Primal Hydralisk[10],Yeti(M)[4]"],
        ["Destroyer", "Hidden", "Hybrid", "Mohandar(X+,90%+)[1]+Hercules Bomber(X+,90%+)[1]", "Vulture-MinePlant[24],Diamondback[13],Spartan Company[12],Siege Breaker[16],Dark Zealot[2],Dark Sentry[6],Dark Stalker[10],Dark Immortal[14]"],
        ["Hybrid Nemesis", "Hidden", "Hybrid", "Brood Lord(X+,90%+)[1]+Tassadar(X+)[2]", "Warmonger[1],Sniper[1],Hammer Securities[2],Dark Zealot[2],Dark High Templar[6],Dark Archon[8],Primal Roach[3],Primal Lurker[13],Primal Hydralisk[8]"],
        ["Hybrid Mobius", "Hidden", "Hybrid", "Pirate Capital Ship(X+,Limit Break 3+)[1]+Tal'Darim Mothership(X+,Limit Break 3+)[1]+God of Time (Skill Used)[1]", "Diamondback[14],Spartan Company[14],Siege Breaker[28],Dark Archon[8],Dark Sentry[12],Dark Stalker[6],Dark Immortal[26],God of Time[1]"],
        ["Hybrid Behemoth", "Hidden", "Hybrid", "Alarak(X+,90%+)[1]+General Warfield(X+)[2]", "Warmonger[3],Sniper[11],Hammer Securities[14],Dark High Templar[13],Dark Zealot[9],Dark Archon[6],Primal Roach[2],Primal Lurker[2],Primal Hydralisk[4]"],
        ["The Last Dominator", "Hidden", "Hybrid", "Sarah Kerrigan(XD+,200%+,Lv11)[1]+Hybrid Behemoth(XD+,200%+,Lv11)[1]", "Warmonger[7],Sniper[15],Hammer Securities[22],Dark Zealot[13],Dark High Templar[17],Dark Archon[14],Primal Roach[8],Primal Lurker[12],Primal Hydralisk[20]"],
        ["Narud", "SuperHidden", "Hybrid", "Void Thrasher(SXD,300%+,300~999kills)[2]+Sarah Kerrigan(X+,150%+)[2]", "Warmonger[12],Sniper[12],Hammer Securities[24],Diamondback[26],Spartan Company[24],Siege Breaker[32],Dark Zealot[18],Dark High Templar[30],Dark Archon[44],Dark Sentry[12],Dark Stalker[20],Dark Immortal[32],Primal Roach[18],Primal Lurker[46],Primal Hydralisk[48],Vulture-MinePlant[48]"]
    ]
};